name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # La indentación de los siguientes paquetes debe ser de 2 espacios.
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: ^0.20.0
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2  
  jwt_decode: ^0.3.1 # <-- AÑADE ESTA LÍNEA

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/areas/