name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: ^0.20.0
  http: ^1.2.1                  # <-- AÑADE ESTA LÍNEA
  flutter_secure_storage: ^9.0.0 # <-- Y ESTA LÍNEA
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Para añadir assets a tu aplicación, añade una sección de assets como esta:
  assets:
    - assets/images/
    - assets/images/areas/ # <-- AÑADE ESTA LÍNEA PARA LA NUEVA CARPETA